// <auto-generated />
using System;
using LetrerosHerreraSYNCTIMEapi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LetrerosHerreraSYNCTIMEapi.Migrations
{
    [DbContext(typeof(LetrerosHerreradbContext))]
    [Migration("20260907032609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("CanalPreferido")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("canal_preferido")
                        .HasDefaultValue("web", "DF_clientes_canal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_clientes_fecha");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.HasIndex(new[] { "Telefono" }, "UQ_clientes_telefono")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.CotizacionDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<decimal>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad")
                        .HasDefaultValue(1m, "DF_detalle_cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal?>("Subtotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 4)")
                        .HasColumnName("subtotal")
                        .HasComputedColumnSql("([cantidad]*[precio_unitario])", true);

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdCotizacion");

                    b.HasIndex("IdProducto");

                    b.ToTable("cotizacion_detalle", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Cotizacione", b =>
                {
                    b.Property<int>("IdCotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCotizacion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValue("pendiente", "DF_cotizaciones_estado");

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_emision")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_cotizaciones_fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int?>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total");

                    b.Property<int>("ValidezDias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("validez_dias")
                        .HasDefaultValue(15, "DF_cotizaciones_validez");

                    b.HasKey("IdCotizacion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdSolicitud");

                    b.HasIndex(new[] { "IdCliente" }, "IX_cotizaciones_cliente");

                    b.ToTable("cotizaciones", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasDefaultValue(true, "DF_empleados_activo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("fecha_ingreso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol")
                        .HasDefaultValue("operario", "DF_empleados_rol");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpleado");

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.FechasComprometida", b =>
                {
                    b.Property<int>("IdFecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_fecha");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFecha"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValue("reservado", "DF_fechas_estado");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<TimeOnly?>("HoraEstimada")
                        .HasColumnType("time")
                        .HasColumnName("hora_estimada");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.HasKey("IdFecha");

                    b.HasIndex("IdPedido");

                    b.ToTable("fechas_comprometidas", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.HorariosAtencion", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_horario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("estado")
                        .HasDefaultValue("disponible", "DF_horarios_estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Nota")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nota");

                    b.HasKey("IdHorario");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("horarios_atencion", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Materiale", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_material");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("categoria");

                    b.Property<decimal>("CostoUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo_unitario");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("StockActual")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("stock_actual");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdMaterial");

                    b.HasIndex(new[] { "IdProveedor" }, "IX_materiales_proveedor");

                    b.ToTable("materiales", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.MovimientosInventario", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_movimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_movimientos_fecha");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("id_material");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("motivo");

                    b.Property<int?>("ReferenciaPedido")
                        .HasColumnType("int")
                        .HasColumnName("referencia_pedido");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("ReferenciaPedido");

                    b.HasIndex(new[] { "IdMaterial", "Fecha" }, "IX_movimientos_material_fecha");

                    b.ToTable("movimientos_inventario", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Notificacione", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_notificacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("canal")
                        .HasDefaultValue("gmail", "DF_notificaciones_canal");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("destinatario");

                    b.Property<string>("EstadoEnvio")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado_envio")
                        .HasDefaultValue("enviado", "DF_notificaciones_estado");

                    b.Property<DateTime>("FechaEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_envio")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_notificaciones_fecha");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.HasKey("IdNotificacion");

                    b.HasIndex(new[] { "IdSolicitud" }, "IX_notificaciones_solicitud");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValue("en_proceso", "DF_pedidos_estado");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_pedido")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_pedidos_fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdCotizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion");

                    b.Property<int?>("IdEmpleadoAsignado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado_asignado");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("prioridad")
                        .HasDefaultValue("media", "DF_pedidos_prioridad");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCotizacion");

                    b.HasIndex("IdEmpleadoAsignado");

                    b.HasIndex(new[] { "IdCliente" }, "IX_pedidos_cliente");

                    b.HasIndex(new[] { "Estado" }, "IX_pedidos_estado");

                    b.HasIndex(new[] { "IdSolicitud" }, "UQ_pedidos_solicitud")
                        .IsUnique();

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.PedidoMaterial", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("id_material");

                    b.Property<decimal>("CantidadUtilizada")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad_utilizada");

                    b.HasKey("IdPedido", "IdMaterial");

                    b.HasIndex("IdMaterial");

                    b.ToTable("pedido_material", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.ProductoMaterial", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdMaterial")
                        .HasColumnType("int")
                        .HasColumnName("id_material");

                    b.Property<decimal>("CantidadRequerida")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad_requerida");

                    b.HasKey("IdProducto", "IdMaterial");

                    b.HasIndex("IdMaterial");

                    b.ToTable("producto_material", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.ProductosServicio", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_base");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("IdProducto");

                    b.HasIndex(new[] { "Nombre" }, "UQ_productos_nombre")
                        .IsUnique();

                    b.ToTable("productos_servicios", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Proveedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("contacto");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_solicitud");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cantidad")
                        .HasDefaultValue(1, "DF_solicitudes_cantidad");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado")
                        .HasDefaultValue("pendiente", "DF_solicitudes_estado");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_decision");

                    b.Property<DateTime>("FechaSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_solicitud")
                        .HasDefaultValueSql("(sysutcdatetime())", "DF_solicitudes_fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("MaterialSolicitado")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("material_solicitado");

                    b.Property<string>("NotasWhatsapp")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("notas_whatsapp");

                    b.Property<string>("Tamano")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tamano");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono_contacto");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "IdCliente" }, "IX_solicitudes_cliente");

                    b.HasIndex(new[] { "Estado" }, "IX_solicitudes_estado");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("activo")
                        .HasDefaultValue(true, "DF_usuarios_activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rol")
                        .HasDefaultValue("operario", "DF_usuarios_rol");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex(new[] { "Email" }, "UQ_usuarios_email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.CotizacionDetalle", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Cotizacione", "IdCotizacionNavigation")
                        .WithMany("CotizacionDetalles")
                        .HasForeignKey("IdCotizacion")
                        .IsRequired()
                        .HasConstraintName("FK_detalle_cotizacion");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.ProductosServicio", "IdProductoNavigation")
                        .WithMany("CotizacionDetalles")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_detalle_producto");

                    b.Navigation("IdCotizacionNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Cotizacione", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_cotizaciones_cliente");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_cotizaciones_empleado");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", "IdSolicitudNavigation")
                        .WithMany("Cotizaciones")
                        .HasForeignKey("IdSolicitud")
                        .HasConstraintName("FK_cotizaciones_solicitud");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.FechasComprometida", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("FechasComprometida")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK_fechas_pedido");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.HorariosAtencion", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("HorariosAtencions")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_horarios_empleado");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Materiale", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Materiales")
                        .HasForeignKey("IdProveedor")
                        .HasConstraintName("FK_materiales_proveedor");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.MovimientosInventario", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_movimientos_empleado");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Materiale", "IdMaterialNavigation")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_movimientos_material");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Pedido", "ReferenciaPedidoNavigation")
                        .WithMany("MovimientosInventarios")
                        .HasForeignKey("ReferenciaPedido")
                        .HasConstraintName("FK_movimientos_pedido");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdMaterialNavigation");

                    b.Navigation("ReferenciaPedidoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Notificacione", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", "IdSolicitudNavigation")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdSolicitud")
                        .IsRequired()
                        .HasConstraintName("FK_notificaciones_solicitud");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Pedido", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_pedidos_cliente");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Cotizacione", "IdCotizacionNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdCotizacion")
                        .HasConstraintName("FK_pedidos_cotizacion");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Empleado", "IdEmpleadoAsignadoNavigation")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdEmpleadoAsignado")
                        .HasConstraintName("FK_pedidos_empleado");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", "IdSolicitudNavigation")
                        .WithOne("Pedido")
                        .HasForeignKey("LetrerosHerreraSYNCTIMEapi.Models.Pedido", "IdSolicitud")
                        .IsRequired()
                        .HasConstraintName("FK_pedidos_solicitud");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdCotizacionNavigation");

                    b.Navigation("IdEmpleadoAsignadoNavigation");

                    b.Navigation("IdSolicitudNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.PedidoMaterial", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Materiale", "IdMaterialNavigation")
                        .WithMany("PedidoMaterials")
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_pedido_material_material");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("PedidoMaterials")
                        .HasForeignKey("IdPedido")
                        .IsRequired()
                        .HasConstraintName("FK_pedido_material_pedido");

                    b.Navigation("IdMaterialNavigation");

                    b.Navigation("IdPedidoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.ProductoMaterial", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Materiale", "IdMaterialNavigation")
                        .WithMany("ProductoMaterials")
                        .HasForeignKey("IdMaterial")
                        .IsRequired()
                        .HasConstraintName("FK_producto_material_material");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.ProductosServicio", "IdProductoNavigation")
                        .WithMany("ProductoMaterials")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_producto_material_producto");

                    b.Navigation("IdMaterialNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_solicitudes_cliente");

                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.ProductosServicio", "IdProductoNavigation")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_solicitudes_producto");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Usuario", b =>
                {
                    b.HasOne("LetrerosHerreraSYNCTIMEapi.Models.Empleado", "IdEmpleadoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpleado")
                        .HasConstraintName("FK_usuarios_empleado");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Cliente", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Pedidos");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Cotizacione", b =>
                {
                    b.Navigation("CotizacionDetalles");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Empleado", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("HorariosAtencions");

                    b.Navigation("MovimientosInventarios");

                    b.Navigation("Pedidos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Materiale", b =>
                {
                    b.Navigation("MovimientosInventarios");

                    b.Navigation("PedidoMaterials");

                    b.Navigation("ProductoMaterials");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Pedido", b =>
                {
                    b.Navigation("FechasComprometida");

                    b.Navigation("MovimientosInventarios");

                    b.Navigation("PedidoMaterials");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.ProductosServicio", b =>
                {
                    b.Navigation("CotizacionDetalles");

                    b.Navigation("ProductoMaterials");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Proveedore", b =>
                {
                    b.Navigation("Materiales");
                });

            modelBuilder.Entity("LetrerosHerreraSYNCTIMEapi.Models.Solicitude", b =>
                {
                    b.Navigation("Cotizaciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Pedido");
                });
#pragma warning restore 612, 618
        }
    }
}
